name: Metrics Web Application Actions

on:
  push:
    branches: master
    paths:
      - metrics/web/**
      - metrics/core/**

jobs:
  metrics-actions:
    name: Metrics actions
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TEST
        run: echo TEST
      - name: Download Ci integrations
        run: |
          curl -o metrics_cli -k https://github.com/solid-dimakoniaiev/flank-dashboard/releases/download/metrics-cli-snapshot/metrics_cli_macos -L
          chmod a+x metrics_cli
      - name: Apply environment variables
        env:
          FIREBASE_AUTH_TOKEN: auth_token
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GOOGLE_SIGN_IN_CLIENT_ID: ${{ secrets.GOOGLE_SIGN_IN_CLIENT_ID }}
          SENTRY_AUTH_TOKEN: auth_token
          ORGANIZATION_SLUG: ${{ secrets.ORGANIZATION_SLUG }}
          PROJECT_SLUG: ${{ secrets.PROJECT_SLUG }}
          PROJECT_DSN: ${{ secrets.PROJECT_DSN }}
          RELEASE_NAME: ${{ secrets.RELEASE_NAME }}
        run: |
          eval "echo \"$(sed 's/"/\\"/g' update_config.yml)\"" >> update.yml
          echo 100
          cat update.yml
          echo 200
        working-directory: .metrics/
      - name: Coverage Converter build data sync
        run: ./metrics_cli update --config-file=".metrics/update.yml"