name: Metrics Web Application Actions

on:
  push:
    branches: master
    paths:
      - metrics/web/**
      - metrics/core/**

jobs:
  metrics-actions:
    name: Metrics actions
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Secret Security
        run: |
          echo 100
          echo $TEST_SECRET
          echo 200