name: Metrics Web Application Actions

on:
  push:
    branches: master
    paths:
      - metrics/web/**
      - metrics/core/**

jobs:
  metrics-actions:
    name: Metrics actions
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Secret Security
        run: |
          echo 100
          cd metrics/web
          echo 200
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - name: Firebase use
        run: firebase use $PROJECT_ID